### ISSUE TITLE
[umbrella] Configuration enhancements

### ISSUE THREAD

**Issue by yikf** [yikf/incubator-gluten#10]
### Description

As discussed in https://github.com/apache/incubator-gluten/issues/6970, we plan to enhance the gluten configuration, and the specific enhancement solutions can be found in section https://github.com/apache/incubator-gluten/issues/6970#issuecomment-2511452471.

This issue serves as an umbrella to record the task list that we need to include to achieve our goals, because enhance config involves a large number of files, splitting multiple tasks facilitates code review and reduces the risk of introducing other problems.

- [ ] Introduce the ConfigEntry to make the config definition more flexible.
- [ ] Split the configuration into individual modules that belong to each other.
- [ ] Split configuration into two separate files: one static and one non-static.
- [ ] Standardize configuration naming, log the deprecated config name if used.
- [ ] Support generate gluten configuration doc and check it. https://github.com/apache/incubator-gluten/issues/8070

**Comment by baibaichen** [comment]
@yikf FYI

Here are some my own summaries about characteristics of configuration:
1. The configuration at startup cannot be dynamically changed
2. Configurations that can be changed per query(i.e. session)
3. Configurations that only affects the configuration of the driver
4. Configurations that needs to be passed to the worker, that is, the backend configuration, not the Spark configuration
5. Spark configurations that needs to be passed to backend, for example, `spark.sql.caseSensitive`

**Comment by FelixYBW** [comment]
@yikf Is the enhancement finished? Is there a readme about how to add a configuration?
